p8105_hw2_tl3195
================
Tingyi Li
2023-10-04

load libraries

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

# Problem 1

Clean the data in `pols-month.csv`:

Use `separate()` to break up the variable `mon` into integer variables
`year`, `month`, and `day`. Replace month number with month name. Create
a `president` variable taking values `gop` and `dem`, and remove
`prez_dem` and `prez_gop`; and remove the day variable.

``` r
pols_month = read.csv("./fivethirtyeight_datasets/pols-month.csv") |>
  janitor::clean_names()|>
  separate(mon,into=c("year","month","day"))|>
  mutate(month = month.name[as.numeric(month)],
         president=
           case_match(prez_gop, 0~"democratic", 1~"republican", 2~"republican")
        )|>
  select(-prez_dem,-prez_gop,-day)
```

Clean snp.csv with a similar process:

arrange according to year and month, and organize so that `year` and
`month` are the leading columns.

``` r
snp = read_csv("./fivethirtyeight_datasets/snp.csv",
    col_types = cols(date = col_date(format = "%m/%d/%y"))) |>
  separate(date, into = c("year", "month", "day"), convert = TRUE) |>
  mutate(month = month.name[as.numeric(month)],
         year = if_else(year > 2023, year - 100, year)) |> 
  select(year, month, close) 
```

Tidy the unemployment data so that it can be merged with the previous
datasets.

Switching from “wide” to “long” format. Ensuring that key variables have
the same name. Ensuring that key variables have the same values.

``` r
unemployment = read_csv("./fivethirtyeight_datasets/unemployment.csv") |>
  rename(year = Year) |>
  pivot_longer(
    Jan:Dec, 
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  mutate(month=month.name[match(month,month.abb)])|>
  mutate(year=as.character(year))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Join the datasets by merging `snp` into `pols`, and merging
`unemployment` into the result.

``` r
pols_month$year <- as.numeric(pols_month$year)
snp$year <- as.numeric(snp$year)
unemployment$year <- as.numeric(unemployment$year)

data=pols_month |>
  left_join(snp, by=c("year", "month")) |>
  left_join(unemployment, by=c("year", "month"))

str(data)
```

    ## 'data.frame':    822 obs. of  11 variables:
    ##  $ year        : num  1947 1947 1947 1947 1947 ...
    ##  $ month       : chr  "January" "February" "March" "April" ...
    ##  $ gov_gop     : int  23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_gop     : int  51 51 51 51 51 51 51 51 51 51 ...
    ##  $ rep_gop     : int  253 253 253 253 253 253 253 253 253 253 ...
    ##  $ gov_dem     : int  23 23 23 23 23 23 23 23 23 23 ...
    ##  $ sen_dem     : int  45 45 45 45 45 45 45 45 45 45 ...
    ##  $ rep_dem     : int  198 198 198 198 198 198 198 198 198 198 ...
    ##  $ president   : chr  "democratic" "democratic" "democratic" "democratic" ...
    ##  $ close       : num  NA NA NA NA NA NA NA NA NA NA ...
    ##  $ unemployment: num  NA NA NA NA NA NA NA NA NA NA ...

Description There exists some “NA” in both “close” and “unemployment”
columns, which indicates that it’s the missing value. The `pols-month`
data has 822 observations and 9 variables and the variables are `year`,
`month`, `gov_gop`, `sen_gop`, `rep_gop`, `gov_dem`, `sen_dem`,
`rep_dem`, `president`. It tells us about whether governers belongs to
democratic or republican. Moreover, we also know that the variable
`year` ranges from 1947 to 2015. The `snp` data has 787 observations and
3 variables and the variables are `year`, `month`, and `close`. The
varibale `year` ranges from 1950 to 2015. The `unemployment` data has
816 observations and 3 variables ranging from years 1948 to 2015. The
merged dataset `data` has 822 observations and 11 variables and the
variables are `year`, `month`, `gov_gop`, `sen_gop`, `rep_gop`,
`gov_dem`, `sen_dem`, `rep_dem`, `president`, `close`, and
`unemployment`. The variable `year` ranges from 1947 to 2015.

# Problem 2

Read and clean the Mr. Trash Wheel sheet:

Specify the sheet in the Excel file and to omit non-data entries (rows
with notes / figures; columns containing notes) using arguments in
`read_excel` Use reasonable variable names Omit rows that do not include
dumpster-specific data Update the data to include a new `homes_powered`
variable based on this calculation: Homes Powered - Each ton of trash
equates to on average 500 kilowatts of electricity. An average household
will use 30 kilowatts per day.

``` r
mr_trash_wheel = read_excel(
  "202309 Trash Wheel Collection Data.xlsx", 
  sheet="Mr. Trash Wheel", range = cell_cols("A:N"))|>
  janitor::clean_names()|>
  filter(row_number() <= n()-1)|>
  mutate(homes_powered=weight_tons*500/30)

mr_trash_wheel
```

    ## # A tibble: 584 × 14
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 574 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>

Professor Trash Wheel with a similar process

``` r
professor_trash_wheel = read_excel(
  "202309 Trash Wheel Collection Data.xlsx", 
  sheet="Professor Trash Wheel", range = cell_cols("A:M"))|>
  janitor::clean_names()|>
  filter(row_number() <= n()-1)|>
  mutate(homes_powered=weight_tons*500/30)

professor_trash_wheel
```

    ## # A tibble: 106 × 13
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 96 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>

Gwynnda with a similar process

``` r
gwynnda_trash_wheel = read_excel(
  "202309 Trash Wheel Collection Data.xlsx", 
  sheet="Gwynnda Trash Wheel", range = cell_cols("A:L"))|>
  janitor::clean_names()|>
  filter(row_number() <= n()-2)|>
  mutate(homes_powered=weight_tons*500/30)

gwynnda_trash_wheel
```

    ## # A tibble: 155 × 12
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 145 more rows
    ## # ℹ 6 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>

Combine these with the Mr. Trash Wheel dataset to produce a single tidy
dataset. To keep track of which Trash Wheel is which, I add an
additional variable called `trashwheel` to all datasets before
combining.

``` r
mr_trash_wheel=mr_trash_wheel |>
  mutate(trashwheel="Mr. Trash Wheel",
         year=as.numeric(year))

professor_trash_wheel=professor_trash_wheel |>
  mutate(trashwheel="Professor Trash Wheel")

gwynnda_trash_wheel=gwynnda_trash_wheel |>
  mutate(trashwheel="Gwynnda Trash Wheel")

mr_trash_wheel_tidy = 
  bind_rows(mr_trash_wheel, professor_trash_wheel, gwynnda_trash_wheel) |>
  janitor::clean_names() |>
  select(trashwheel, everything())

mr_trash_wheel_tidy
```

    ## # A tibble: 845 × 15
    ##    trashwheel      dumpster month  year date                weight_tons
    ##    <chr>              <dbl> <chr> <dbl> <dttm>                    <dbl>
    ##  1 Mr. Trash Wheel        1 May    2014 2014-05-16 00:00:00        4.31
    ##  2 Mr. Trash Wheel        2 May    2014 2014-05-16 00:00:00        2.74
    ##  3 Mr. Trash Wheel        3 May    2014 2014-05-16 00:00:00        3.45
    ##  4 Mr. Trash Wheel        4 May    2014 2014-05-17 00:00:00        3.1 
    ##  5 Mr. Trash Wheel        5 May    2014 2014-05-17 00:00:00        4.06
    ##  6 Mr. Trash Wheel        6 May    2014 2014-05-20 00:00:00        2.71
    ##  7 Mr. Trash Wheel        7 May    2014 2014-05-21 00:00:00        1.91
    ##  8 Mr. Trash Wheel        8 May    2014 2014-05-28 00:00:00        3.7 
    ##  9 Mr. Trash Wheel        9 June   2014 2014-06-05 00:00:00        2.52
    ## 10 Mr. Trash Wheel       10 June   2014 2014-06-11 00:00:00        3.76
    ## # ℹ 835 more rows
    ## # ℹ 9 more variables: volume_cubic_yards <dbl>, plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   plastic_bags <dbl>, wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>

Description `trashwheel` is a new variable that I have created in
`mr_trash_wheel_tidy` dataset. Specifically, “Mr. Trash Wheel” indicates
that the type of trashwheel is Mr. Trash Wheel. “Professor Trash Wheel”
indicates that the type of trashwheel is Professor Trash Wheel. “Gwynnda
Trash Wheel” indicates that the type of trashwheel is Gwynnda Trash
Wheel. `home_powered` is a variable calculated by weight_tons\*500/30.
Specifically, Each ton of trash equates to on average 500 kilowatts of
electricity. An average household will use 30 kilowatts per day. The
resulting dataset, as known as `mr_trash_wheel_tidy` has 845
observations and 15 variables. The variables include `trashwheel`,
`dumpster`, `month`, `year`, `date`, `weight_tons`, `volume_cubic_yard`,
`plastic_bottles`, `polystyrene`, `cigarette_butts`, `glass_bottles`,
`plastic_bags`, `wrappers`, `sports_balls`, and `home_powered`. The
total weight of trash collected by Professor Trash Wheel was 216.26
tons. The total number of cigarette butts collected by Gwynnda in July
of 2021 was 1.63^{4}.

# Problem 3

Import, clean, and tidy the dataset of baseline demographics:

Ensure that sex and APOE4 carrier status are appropriate encoded
(i.e. not numeric). Remove any participants who do not meet the stated
inclusion criteria (i.e. no MCI at baseline).

``` r
mci_baseline = read_csv("./data_mci/MCI_baseline.csv", skip = 1) |>
  janitor::clean_names() |>
  mutate(
    sex = 
      case_match(
        sex,
        1 ~ "Male",
        0 ~ "Female"),
    sex = as.factor(sex),
    apoe4 =
      case_match(
        apoe4,
        1 ~ "APOE4 carrier",
        0 ~ "APOE4 non-carrier"),
    apoe4 = as.factor(apoe4),
    age_at_onset = ifelse(age_at_onset==".", NA, age_at_onset),
    age_at_onset = as.numeric(age_at_onset)
    ) |>
  drop_na(age_at_onset)
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
mci_baseline
```

    ## # A tibble: 97 × 6
    ##       id current_age sex    education apoe4             age_at_onset
    ##    <dbl>       <dbl> <fct>      <dbl> <fct>                    <dbl>
    ##  1     3        62.5 Male          16 APOE4 carrier             66.8
    ##  2     5        66   Male          16 APOE4 non-carrier         68.7
    ##  3     7        66.5 Male          18 APOE4 non-carrier         74  
    ##  4    13        63.1 Male          12 APOE4 carrier             69  
    ##  5    14        58.4 Female        20 APOE4 non-carrier         66.2
    ##  6    18        67.8 Male          16 APOE4 non-carrier         69.8
    ##  7    22        67.3 Female        20 APOE4 carrier             74.6
    ##  8    26        64.8 Female        20 APOE4 carrier             71.1
    ##  9    30        66.3 Female        12 APOE4 non-carrier         73.1
    ## 10    39        68.3 Female        16 APOE4 carrier             70.2
    ## # ℹ 87 more rows

Description When importing `mci_baseline` dataset, we need to use
`skip=1` to skip the first line which is the description of each
variable. Use `janitor::clean_names()` to convert every variable name to
lowercase. Use `case_match()` for `sex` and `apoe4` to convert to the
specific categories and meaning of both of them rather than 0 and 1. Use
`drop_na(age_at_onset)` to drop missing values in the variable
`age_at_onset`. Before using `drop_na()`, we need to first convert “.”
into “NA” by using `ifelse()`.

Relevant features of dataset: The datset `mci_baseline` has 97
observations and 6 variables. The variables include `id`, `current_age`
(years), `sex`(female vs male), `education` (years), `apoe4` (carrier vs
non-carrier), and `age_at_onset`. 483 participants were recruited, and
of these 97 developed MCI. The average baseline age was 65.61 years. The
proportion of women in the study are APOE4 carriers is equal to P(apoe4
carriers\|women who developed MCI)=0.65.

Import, clean, and tidy the dataset of longitudinally observed biomarker
values with similar processes.

Comment on the steps on the import process and the features of the
dataset.

``` r
mci_amyloid = read_csv("./data_mci/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names() |>
  rename(id=study_id) |>
  pivot_longer(
    time_2:time_8,
    names_to = "time",
    values_to = "amyloid") |>
  mutate(
    time = 
      case_match(
        time,
        "time_2" ~ 2,
        "time_4" ~ 4 ,
        "time_6" ~ 6,
        "time_8" ~ 8),
    time = as.numeric(time),
    baseline = as.numeric(baseline),
    amyloid = as.numeric(amyloid)
  ) 
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There were 2 warnings in `mutate()`.
    ## The first warning was:
    ## ℹ In argument: `baseline = as.numeric(baseline)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion
    ## ℹ Run `dplyr::last_dplyr_warnings()` to see the 1 remaining warning.

``` r
mci_amyloid  
```

    ## # A tibble: 1,948 × 4
    ##       id baseline  time amyloid
    ##    <dbl>    <dbl> <dbl>   <dbl>
    ##  1     1    0.111     2  NA    
    ##  2     1    0.111     4   0.109
    ##  3     1    0.111     6   0.105
    ##  4     1    0.111     8   0.107
    ##  5     2    0.107     2   0.109
    ##  6     2    0.107     4   0.109
    ##  7     2    0.107     6   0.106
    ##  8     2    0.107     8   0.107
    ##  9     3    0.106     2   0.109
    ## 10     3    0.106     4   0.106
    ## # ℹ 1,938 more rows

Description When importing `mci_amyloid` dataset, we need to use
`skip=1` to skip the first line which is the description of each
variable. Use `janitor::clean_names()` to convert every variable name to
lowercase. Use `pivot_long` to change the `mci_amyloid` dataset from
wide format to long format, which is easier for data manipulation. Use
`case_match()` for `time` to convert `time_2`, `time_4`, `time_6` and
`time_8` to specfic numbers 2, 4, 6, and 8,respectively.

Relevant features: The dataset `mci_amyloid` has 1948 observations and 4
variables. The variables include `id`, `baseline`, `time`, and
`amyloid`.

Check whether some participants appear in only the baseline or amyloid
datasets, and comment on your findings.

Participants only in baseline dataset:

``` r
mci_baseline_only <- anti_join(mci_baseline, mci_amyloid, by = "id")

unique(mci_baseline_only$id)
```

    ## [1]  14  49 268

Participants only in amyloid dataset:

``` r
mci_amyloid_only <- anti_join(mci_amyloid, mci_baseline, by = "id")
unique(mci_amyloid_only$id)
```

    ##   [1]   1   2   4   6   8   9  10  11  12  15  16  17  19  20  21  23  24  25
    ##  [19]  27  28  29  31  32  33  34  35  36  37  38  40  41  42  44  46  47  48
    ##  [37]  50  51  52  53  54  56  57  58  60  61  62  63  64  66  68  70  71  73
    ##  [55]  74  79  80  81  82  83  84  85  88  90  91  93  94  95  96  97  98  99
    ##  [73] 100 101 102 103 104 105 107 108 110 111 112 113 114 115 116 117 118 119
    ##  [91] 121 122 124 125 126 127 128 129 130 131 133 134 135 136 137 138 139 140
    ## [109] 141 142 143 144 145 147 148 150 151 152 153 154 155 156 157 158 159 160
    ## [127] 161 162 163 164 165 167 168 169 171 172 173 174 175 176 178 180 181 182
    ## [145] 183 184 185 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201
    ## [163] 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 219 220 221
    ## [181] 222 223 224 225 227 228 231 232 233 235 236 237 238 239 240 241 243 244
    ## [199] 245 246 247 248 251 253 254 255 256 257 258 259 260 261 262 263 264 265
    ## [217] 266 267 269 270 271 272 273 274 275 276 278 279 281 282 284 285 288 290
    ## [235] 291 293 294 295 296 298 299 300 302 303 307 308 309 310 311 312 313 315
    ## [253] 316 317 318 319 320 321 322 324 325 326 327 329 330 331 332 333 334 335
    ## [271] 339 340 341 342 343 344 345 346 353 354 356 357 358 359 360 361 362 363
    ## [289] 364 367 368 370 371 372 374 375 376 378 381 382 383 384 385 386 387 388
    ## [307] 390 391 392 393 394 395 396 397 399 401 402 403 404 405 406 407 410 411
    ## [325] 413 414 415 418 420 421 422 425 427 428 429 430 432 433 434 435 436 437
    ## [343] 438 439 441 443 444 445 446 447 450 451 454 455 456 457 458 459 460 461
    ## [361] 462 463 464 465 466 467 468 469 470 472 473 474 475 476 477 478 479 480
    ## [379] 481 482 483 484 485 486 487 488 489 490 491 492 493 494 495

According to the results, it’s apparent that there are some participants
appear in only the baseline dataset and there are some participants
appear in only the amyloid dataset.

Combine the demographic and biomarker datasets so that only participants
who appear in both datasets are retained, and briefly describe the
resulting dataset. Export the result as a CSV to your data directory.

``` r
combined_data <- inner_join(mci_baseline, mci_amyloid, by = "id")

combined_data
```

    ## # A tibble: 376 × 9
    ##       id current_age sex   education apoe4   age_at_onset baseline  time amyloid
    ##    <dbl>       <dbl> <fct>     <dbl> <fct>          <dbl>    <dbl> <dbl>   <dbl>
    ##  1     3        62.5 Male         16 APOE4 …         66.8    0.106     2   0.109
    ##  2     3        62.5 Male         16 APOE4 …         66.8    0.106     4   0.106
    ##  3     3        62.5 Male         16 APOE4 …         66.8    0.106     6  NA    
    ##  4     3        62.5 Male         16 APOE4 …         66.8    0.106     8   0.106
    ##  5     5        66   Male         16 APOE4 …         68.7    0.108     2   0.112
    ##  6     5        66   Male         16 APOE4 …         68.7    0.108     4   0.115
    ##  7     5        66   Male         16 APOE4 …         68.7    0.108     6   0.107
    ##  8     5        66   Male         16 APOE4 …         68.7    0.108     8   0.106
    ##  9     7        66.5 Male         18 APOE4 …         74      0.112     2  NA    
    ## 10     7        66.5 Male         18 APOE4 …         74      0.112     4   0.104
    ## # ℹ 366 more rows

Description The `combined_data` dataset has 376 observations and 9
variables. The variables include `id`, `current_age` (years), `sex`
(female vs male), `education` (years), `apoe4` (carrier vs non-carrier),
`age_at_onset`, `baseline`, `time` and `amyloid`.

Export the result as a CSV to the data directory

``` r
write_csv(combined_data, file = "./data/output_results.csv")
```
